### PR TITLE
Fix energy weapons draining before unit completion. Fixes #2172

### LINKED ISSUE #2172: Arty drains resources for loading before it's finished
Start any arty structure or UEF T3 PD (or whatever needs energy to shoot) and you get this:

obrazek

No error in the log

### PR DESCRIPTION
**Pull request by basdawimp**
Fixes #2172

### CODE REVIEW

File: lua/sim/defaultweapons.lua [hunk 1]
```diff
@@ -163,6 +163,7 @@ DefaultProjectileWeapon = Class(Weapon) {
     -- Create an economy event for those weapons which require Energy to fire
     StartEconomyDrain = function(self)
         if self.FirstShot then return end
+        if self.unit:GetFractionComplete() ~= 1 then retern end
```
Comment (speed2CZ) [inline lua/sim/defaultweapons.lua]: typo here, it should be `return`

Comment (aeoncleanse) [inline lua/sim/defaultweapons.lua]: Holy crap, my brother's spelling. Jesus christ.
