### PR TITLE
Fix Janus and Scorcher tracking bombs

### LINKED ISSUE #2407: Janus bombs track to units and buildings instead of dropping in a line
So this bug will just not die, it's still around and is as bad as ever. It also seems to be present in the scorcher (UEF T1 bomber).

### PR DESCRIPTION
**Pull request by lL1l1**
Resolves #2407.
Greatly improves the bomb dropping pattern of the Janus and Scorcher by making them drop their entire salvo onto one location instead of constantly tracking their target and dropping each individual bomb onto the current predicted target location.
It does change balance for both bombers.
To test, turn on NoDamage in the console, spawn 10 bombers, and spawn a Harbinger as a target for you to micro. The Harbinger turns quickly so it can show off bomb dodging but isn't so fast that the bombing attempt fails like the Spirit. Notice how the Janus doesn't leave giant fiery rings when bombing a turning target.

https://github.com/FAForever/fa/assets/82986251/e17f1c57-8a12-4f36-84a0-49dd0ab74fce

https://github.com/FAForever/fa/assets/82986251/0d2cdb82-fa63-4ba8-82ad-f0d9d0ff3a15

The old "fix" in the weapon script didn't work because `data.usestore` was never set to true. Regardless, it would've had an incorrect bomb trajectory because targetPos was not adjusted for unit speed, while the ballistic acceleration calculation was.

### CODE REVIEW

File: lua/sim/defaultweapons.lua [hunk 1]
```diff
@@ -1089,6 +1097,7 @@ DefaultProjectileWeapon = ClassWeapon(Weapon) {
                 end
             end
 
+            self.CurrentSalvoData = nil
```
Comment (Garanas) [inline lua/sim/defaultweapons.lua:1100]: It is not guaranteed that the code reaches this point, as an example when the target is lost. That is why the salvo data was also reset in the idle state

Comment (lL1l1) [reply lua/sim/defaultweapons.lua:1103]: That is true

**Comment by Garanas** [comment]
This is quite an interesting change, great work 👍 . I'll try to review it this week

**Comment by Garanas** [comment]
Great work @lL1l1
