### PR TITLE
Fix false positive "missing dependency" for UI mods when not host

### LINKED ISSUE #909: Mod manager blocking discreprancy between hosting and joining
The mod blacklist is interpreted differently depending on whether you host or join a game.

Excerpt from a log from joining:

```
warning: {
warning:     D000E905-1E97-420D-8ED9-DF083282F59D = true
warning:     zcbf6277-24e3-437a-b968-Common-v1 = true
warning: }
info: MOD LIST SET TO:
info:         V2 FA Sequentially upgrading extractors       (D000E905-1E97-420D-8ED9-DF083282F59D)
info:         Common Mod Tools        (zcbf6277-24e3-437a-b968-Common-v1)
```

When hosting, ecomanager was allowed.

Needs more investigation.

### PR DESCRIPTION
**Pull request by MrNukealizer**
Fixes #909 and #1186.

### CODE REVIEW

File: lua/ui/lobby/ModsManager.lua [hunk 1]
```diff
@@ -528,8 +528,8 @@ function RefreshModsList()
             if mod.ui_only then
                 -- Is this a UI mod that depends on a sim mod that is turned off?
                 if not IsHost and dependencies.requires then
-                    for innerUid, innerMod in dependencies.requires do
-                        if not innerMod.ui_only and not mods.sim.active[innerUid] then
+                    for innerUid in dependencies.requires do
+                        if not mods.selectable[innerUid]innerMod.ui_only and not mods.sim.active[innerUid] then
```
Comment (duk3luk3) [inline lua/ui/lobby/ModsManager.lua]: You screwed up that line :)

Comment (MrNukealizer) [reply lua/ui/lobby/ModsManager.lua]: Oh crap, I must have accidentally pressed ctrl+z right before saving...

Comment (MrNukealizer) [reply lua/ui/lobby/ModsManager.lua]: ...And fixed.
