### PR TITLE
fix GetAngleInBetween parameter references

### LINKED ISSUE #6524: [Bug]: faf develop scathis does not fire
### Describe the Bug

Once a scathis is built or spawned it will not fire.

Error seen in the logs.

warning: Error running lua script: g:\code\relent0r\fa\lua\utilities.lua(412): attempt to perform arithmetic on local `z2' (a nil value)
         stack traceback:
         	g:\code\relent0r\fa\lua\utilities.lua(412): in function `GetAngleInBetween'
         	g:\code\relent0r\fa\units\url0401\url0401_script.lua(78): in function `CreateProjectileAtMuzzle'
         	...ent0r\fa\lua\sim\weapons\defaultprojectileweapon.lua(1056): in function <...ent0r\fa\lua\sim\weapons\defaultprojectileweapon.lua:969>

### Reproduce the bug

Spawn a scathis with a target to fire at on the current faf develop commit as of 5ae907e3dac7516278c3ff8824bc5ac9e1823c04

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by relent0r**
## Description of the proposed changes
Fixes a small bug in the refactor of GetAngleInBetween. It was references indexes but the function that calls it is using named keys.

fixes #6524

p.s this needs someone smarter than me to validate I'm actually fixes this correctly as I'm unsure.

## Testing done on the proposed changes
Tested to make sure the scathis does not error and shoots things.

## Checklist
- [ ] Changes are annotated, including comments where useful
- [ ] Changes are documented in the changelog for the next game version

### CODE REVIEW

File: lua/utilities.lua [hunk 1]
```diff
@@ -406,12 +406,13 @@ end
 ---@param v2 Vector
 ---@return number
 function GetAngleInBetween(v1, v2)
-    local x1, y1, z2 = v1[1], v1[2], v1[3]
-    local x2, y2, z2 = v2[1], v2[2], v2[3]
+    local x1, y1, z1 = v1.x, v1.y, v1.z
+    local x2, y2, z2 = v2.x, v2.y, v2.z
     -- arccos((v1 . v2) / (|v1| |v2|))
+    local z1Sq = z1 * z1
     local z2Sq = z2 * z2
```
Comment (lL1l1) [inline lua/utilities.lua:413]:
```suggestion
```

File: lua/utilities.lua [hunk 2]
```diff
@@ -406,12 +406,13 @@ end
...
-    local dot = x1*x2 + y1*y2 + z2Sq
-    local len2 = MathSqrt((x1*x1 + y1*y1 + z2Sq) * (x2*x2 + y2*y2 + z2Sq))
+    local dot = x1 * x2 + y1 * y2 + z1 * z2
+    local len2 = MathSqrt((x1 * x1 + y1 * y1 + z1Sq) * (x2 * x2 + y2 * y2 + z2Sq))
```
Comment (lL1l1) [inline lua/utilities.lua:415]:
```suggestion
    local dot = x1 * x2 + y1 * y2 + z1 * z2
    local len2 = MathSqrt((x1 * x1 + y1 * y1 + z1 * z1) * (x2 * x2 + y2 * y2 + z2 * z2))
```

File: lua/utilities.lua [hunk 3]
```diff
@@ -406,12 +406,13 @@ end
 ---@param v2 Vector
 ---@return number
 function GetAngleInBetween(v1, v2)
-    local x1, y1, z2 = v1[1], v1[2], v1[3]
-    local x2, y2, z2 = v2[1], v2[2], v2[3]
+    local x1, y1, z1 = v1.x, v1.y, v1.z
+    local x2, y2, z2 = v2.x, v2.y, v2.z
```
Comment (lL1l1) [inline lua/utilities.lua:410]: I think it's better to fix Scathis to use Vectors (https://github.com/FAForever/fa/commit/00c835fa6894dea25690e2aa36a897d7a0e9c7bd) instead of diverging from how the rest of vector processing code works.
Array access for Vectors is also better than hash access, since it avoids the metamethod that redirects `x` `y` `z` keys to `1` `2` `3` indices.

**Review by lL1l1 — CHANGES_REQUESTED** [review]
Good find for my refactor messing up the mathematics, it should indeed be `z1 * z1` and `z2 * z2`.

I tested the changed math with my fixed Scathis and they make the fake barrels align with the aim barrel more accurately (when you view the wireframe skeletons).

**Comment by lL1l1** [comment]
Note: caused by #6438 
You can also simply add this PR's number to the snippet `other.6438.md` for the changelog requirement, since it is essentially part of the same patch.

**Comment by relent0r** [comment]
> Good find for my refactor messing up the mathematics, it should indeed be `z1 * z1` and `z2 * z2`.
> 
> I tested the changed math with my fixed Scathis and they make the fake barrels align with the aim barrel more accurately (when you view the wireframe skeletons).

Thanks, I can see your making the updates in 6528 for function call, once you merge that in I'll update this to match.

File: lua/utilities.lua (hunk 3 above)
Comment (relent0r) [reply lua/utilities.lua]: Have reverted to using indexes in prep for the other PR.

File: changelog/snippets/other.6438.md [hunk 4]
```diff
@@ -1,4 +1,4 @@
-- (#5061, #6438) Add metamethods and utility functions for Vectors and Quaternions to simplify and clean up the code involving operations with them.
+- (#5061, #6438, #(6525)) Add metamethods and utility functions for Vectors and Quaternions to simplify and clean up the code involving operations with them.
```
Comment (lL1l1) [inline changelog/snippets/other.6438.md:1]:
```suggestion
- (#5061, #6438, #6525) Add metamethods and utility functions for Vectors and Quaternions to simplify and clean up the code involving operations with them.
```
Should remove the extra paranthesis and this can be merged in
