### PR TITLE
Fix various issues with announcements

### LINKED ISSUE #6841: [Bug]: When an objective fails, so does the announcement
### Describe the Bug

Objectives create an announcement when they are created. They also produce one when they are [completed, or failed](https://github.com/FAForever/fa/blob/develop/lua/ui/game/objectives2.lua#L398). The control that is responsible for showing the announcement is destroyed in the same frame, right after the announcement is created.

This is problematic. In the new implementation the [animation is part of a thread](https://github.com/FAForever/fa/blob/develop/lua/ui/game/announcement/AbstractAnnouncement.lua#L302) and therefore when we interact with the control we may already have lost the reference that we need. That produces a load of errors in the log. 

### Reproduce the bug

Play the map 'Rainmakers Survival'. Ignore the warnings about deep copy. Wait for the time-based objective 'The calm before the storm' to finish. See the logs full of errors about functions that no longer exist.

### Screenshots

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Fixes various issues with the new setup for announcements. Closes #6841 .

It fixes the following behavior:

- Re-introduces the callback, which is now called when the announcement is finished. There was 1 place where this was used: objectives to cleanup after themselves when the announcement ends!
- Refactors the animation to be a separate function called `SetupBackgroundAnimation`. The applied animation can then be controlled by setting the progress variable that is returned.
- Fixes an edge case where the animation breaks if the origin/target control is destroyed during the animation.

Also fixes a subtle issue where the position of the origin/target control must be known before we fork a thread. By forking, we push the remaining logic to the end of the internal call stack. In the meantime the control can be destroyed, before the animation even had the time to process it.

## Testing done on the proposed changes

Launched various campaign maps and campaign-like maps to see and verify the interactions with the objectives. Specifically:

- Rainmakers Survival (ignore the initial warnings about deep copying).
- The first campaign map of the FA campaign.

## Checklist

- [x] Changes are annotated, including comments where useful
- [x] Changes are documented in a changelog snippet according to the [guidelines](https://faforever.github.io/fa/development/changelog#format-of-a-snippet).
- [x] Request 2-3 reviewers from the [list of reviewers and their areas of knowledge](https://github.com/FAForever/fa/blob/deploy/fafdevelop/CONTRIBUTING.md#reviewers).

### CODE REVIEW

File: lua/ui/game/announcement.lua [hunk 1]
```diff
@@ -80,15 +81,17 @@ CreateTitleAnnouncement = function(titleText, goalControl)
 
     -- create a dummy goal control if we don't have one
     local frame = GetFrame(0) --[[@as Frame]]
-    goalControl = goalControl or CreateDefaultGoalControl(frame)
+    if not goalControl or IsDestroyed(goalControl) then
```
Comment (4z0t) [inline lua/ui/game/announcement.lua]: `IsDestroyed` already checks for nil.

Comment (Garanas) [reply lua/ui/game/announcement.lua]: Yes, but the plugin does not understand that 😸

Comment (4z0t) [reply lua/ui/game/announcement.lua]: I wonder if 
```lua
---@overload fun(object:nil): true
...
```
will work.

Comment (Garanas) [reply lua/ui/game/announcement.lua]: It appears to not work, unfortunately:

image

Comment (lL1l1) [reply lua/ui/game/announcement.lua]: Searching the issue for the language server they recommend using `---@cast goalControl -nil`.
docs: https://luals.github.io/wiki/annotations/#cast

Comment (lL1l1) [reply lua/ui/game/announcement.lua]: Which results in this:
{74822151-ED75-45AF-A504-EA3B8C2799EB}

Comment (Garanas) [reply lua/ui/game/announcement.lua]: Applied in https://github.com/FAForever/fa/pull/6845/commits/b7068b1f03fcc0160fe6357519c966b39f53b96d
