### PR TITLE
Remove the current implementation to block paintings

### LINKED ISSUE #6806: [Bug]: Able to mute your own paintings
### Describe the Bug

Through https://github.com/FAForever/fa/pull/6783 we mute the paintings of other players when you also mute the chat options. However, because of the same issue as described in #6787 this means in practice that you can mute yourself. Which is of course nonsense. 

### Reproduce the bug

Mute yourself in the chat. Then try to draw. You'll no longer be able to see your own paintings.

### Screenshots

https://github.com/user-attachments/assets/aae3a724-39e1-4f6b-861d-7e82fdca4737

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Garanas**
## Description of the proposed changes

Removes the changes made in https://github.com/FAForever/fa/pull/6783. The current implementation in the chat is buggy. This removes noise on the line, where players are blocked from sharing but you're unable to see that as a player. 

## Testing done on the proposed changes

Launch a game with up to 4 players using the launch script made by Nomander, observe that the paintings work.

## Additional context

This is of course not a great solution, but unfortunately refactoring the chat or its configuration dialog turned out to be very time consuming. We're easily talking about dozens of hours. I do not have the motivation to put in that time. Meanwhile, the current approach of blocking paintings does cause issues with players that do not see paintings at all, sometimes not even their own. 

## Checklist

- [x] Changes are annotated, including comments where useful
- [ ] Changes are documented in a changelog snippet according to the [guidelines](https://faforever.github.io/fa/development/changelog#format-of-a-snippet).
- [ ] Request 2-3 reviewers from the [list of reviewers and their areas of knowledge](https://github.com/FAForever/fa/blob/deploy/fafdevelop/CONTRIBUTING.md#reviewers).

## Summary by CodeRabbit

* **Documentation**
  * Simplified chat filter label and tooltip to remove painting-related wording for clearer guidance.

* **Changes**
  * Painted brush strokes now render consistently in the game interface, regardless of prior per-author filtering.

### CODE REVIEW

**Review by lL1l1 — COMMENTED** [review]
The defaults for the LOC strings also need to be updated. Those are the strings where the LOC function is called.

File: loc/US/strings_db.lua [hunk 1]
```diff
@@ -5639,7 +5639,7 @@ tooltipui0398="Click here to send your message to all of your allies."
 tooltipui0399="All Chat"
 tooltipui0400="Click here to send your message to all players."
 tooltipui0401="Chat Filters"
-tooltipui0402="Show or hide messages and paintings from players"
+tooltipui0402="Show or hide messages from players"
```
Comment (Garanas) [inline loc/US/strings_db.lua:5642]: The default is already `Show or hide messages from players`

**Review by lL1l1 — APPROVED** [review]
