### PR TITLE
check if shield exists before creating impact effects

### LINKED ISSUE #2183: properly cleanup shield threads after death
WARNING: Error running lua script: ...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(218): Game object has been destroyed
         stack traceback:
         	[C]: in function `GetArmy'
         	...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua(218): in function <...rogramdata\faforever\gamedata\lua.nx2\lua\shield.lua:217>

The script needs a few checks if the shield is still alive

### PR DESCRIPTION
**Pull request by CookieNoob**
fixes #2183

### CODE REVIEW

File: lua/shield.lua [hunk 1]
```diff
@@ -215,6 +215,7 @@ Shield = Class(moho.shield_methods, Entity) {
     end,
 
     CreateImpactEffect = function(self, vector)
+        if not self or self.Owner:IsDead() or self.Owner.Dead then return end
```
Comment (aeoncleanse) [inline lua/shield.lua]: self.Owner.Dead only please, IsDead() is deprecated.
