### PR TITLE
Fix not being able to launch AI. Fixes #1370

### LINKED ISSUE #1370: Can't start Game with AI and AI faction is not selectable.
Skirmish and multiplayer:

AI don't has a puldown menu to select faction.
nopulldown

And if any Ai is selected, on buttonpress "gamestart" this error occurs, and the game don't start:

```LUA
WARNING: Error running OnRelease script in <deleted object>: ...03\gamedata\mohodata.scd\lua\system\localization.lua(129): bad argument #2 to `format' (string expected, got nil)
         stack traceback:
         	[C]: in function `format'
         	...03\gamedata\mohodata.scd\lua\system\localization.lua(129): in function `LOCF'
         	...programdata\faforever\repo\fa\lua\ui\lobby\lobby.lua(3251): in function `EveryoneHasEstablishedConnections'
         	...programdata\faforever\repo\fa\lua\ui\lobby\lobby.lua(1578): in function <...programdata\faforever\repo\fa\lua\ui\lobby\lobby.lua:1532>
         	...programdata\faforever\repo\fa\lua\ui\lobby\lobby.lua(2779): in function `OnClick'
         	c:\programdata\faforever\repo\fa\lua\maui\button.lua(85): in function <c:\programdata\faforever\repo\fa\lua\maui\button.lua:78>
```

(Also tried english language. Same effect)
[EDIT] Also tried normal AI, not only Sorian's.

### PR DESCRIPTION
**Pull request by aeoncleanse**

### CODE REVIEW

File: lua/ui/lobby/lobby.lua [hunk 1]
```diff
@@ -679,7 +679,8 @@ function FindObserverSlotForID(id)
 end
 
 function IsLocallyOwned(slot)
-    return (gameInfo.PlayerOptions[slot].OwnerID == localPlayerID)
+    return (gameInfo.PlayerOptions[slot].OwnerID == localPlayerID) or
+        (lobbyComm:IsHost() and gameInfo.PlayerOptions[slot].OwnerID == 999999)
```
Comment (Sheeo) [inline lua/ui/lobby/lobby.lua]: What is this?
